int add (int a, int b);
int sub (int a, int b);
int multi (int a, int b);
double divi (int a, int b);
int fakultat (int a);
int modulo (int a, int b);
double prozent (int a, int b);
int quadrat (int a);
double wurzel (double a);
int untermenu (int a);
int nachrichten (int x);
int palindrom (int x);
int adress (int x);
int spiel (int x);
